			ORG $0000			; s = n1 + n2 + n3 + ... + nn / Datos: n1, n y s
S			RMB	2				; LOAD 506.S19 | PC 8000 | MEM 0 | 0,0,20,00,3 | MEM 2000 | 2,3,5 | RUN
N1			RMB 2				; VALOR ESPERADO EN "S" ($0000): $0A 
N			RMB	1

			ORG $8000
			CLRA				; LIMPIO A
			CLRB				; LIMPIO B
			LDAB	N			; CARGO LA CANTIDAD DE ELEMENTOS AL ACUMULADOR B
			LDX		N1			; CARGO LA POSICION DE MEMORIA N1 EN REGISTRO X
			
LOOP		ADDA	0,X			; SUMO EL CONTENIDO DE LA POSICION GUARDADA EN X AL ACUMULADOR A
			STAA	S+1			; ALMACENO EL CONTENIDO DEL ACUMULADOR A EN LA POSICION DE MEMORIA S
			BCS		CARRY
SIGO		DECB				; DECREMENTO B
			BEQ		FIN			; SI B LLEGA A CERO -> FIN
			INX		1,X			; INCREMENTO EL REGISTRO X CON UN OFFSET DE 1
			BNE		LOOP		; SIGO
			
CARRY	    INC		S
			BRA 	SIGO
			
FIN			BRA		FIN			