			ORG $0000
CANT		RMB	1
VECTOR		RMB 2		
DATO		RMB	1
ELEMENTOS   RMB 1
POSICIONES	RMB 2

			ORG $8000
			LDAB	#2
			CLR		CANT
			LDX		VECTOR
			LDY		POSICIONES
SIGO		LDAA	0,X			
			CMPA	DATO
			BNE		NOES
			INC		CANT
			CLR		0,Y
			STX		0,Y
			ABY
NOES		INX
			DEC		ELEMENTOS
			BNE		SIGO
FIN			BRA		FIN