			ORG $0000
CANT		RMB	1
POSICION	RMB 2
VECTOR		RMB 2		
DATO		RMB	1
ELEMENTOS   RMB 1

			ORG $8000
			CLR		CANT
			LDX		VECTOR
SIGO		LDAA	0,X			
			CMPA	DATO
			BNE		NOES
			INC		CANT
			STX 	POSICION
NOES		INX
			DEC		ELEMENTOS
			BNE		SIGO
FIN			BRA		FIN